In [4]:
%pwd
import os
os.chdir("../")

In [5]:
from Sensor_Fault_Detection.ml.model.estimator import TargetValueMapping
TargetValueMapping().to_dict()

{'negative': 0, 'positive': 1}

In [6]:
TargetValueMapping().reverse_mapping()

{0: 'negative', 1: 'positive'}

In [7]:
path = r"F:\End_To_End_project\Sensor-Fault-Detection\artifact\10_17_2023_22_16_33\data_ingetion\ingested\test.csv"
import pandas  as pd

In [8]:
df = pd.read_csv(path)

In [13]:
from Sensor_Fault_Detection.exception import SensorException
def drop_zero_std_columns(dataframe)->pd.DataFrame:
    try:
        # Filter only numeric columns
        numeric_df = dataframe.select_dtypes(include=[np.number])
        std_dev = numeric_df.std()
        non_zero_std_cols = std_dev[std_dev != 0].index.tolist()
        return dataframe[non_zero_std_cols]
    except Exception as e:
        raise SensorException(e)

In [14]:
drop_zero_std_columns(df)

aa_000        ac_000  ad_000  ae_000  af_000  ag_000  ag_001  ag_002  \
0       7152           NaN     NaN     0.0     0.0     0.0     0.0     0.0   
1        750  1.000000e+01     6.0     0.0     0.0     0.0     0.0     0.0   
2          4  0.000000e+00     0.0     2.0     2.0     0.0     0.0     0.0   
3      81354  2.130706e+09   156.0     0.0     0.0     0.0     0.0     0.0   
4         14  2.130706e+09    14.0     0.0     0.0     0.0     0.0     0.0   
...      ...           ...     ...     ...     ...     ...     ...     ...   
7233   21008  1.200000e+02   132.0     0.0     0.0     0.0     0.0     0.0   
7234   40994  8.200000e+02   768.0     0.0     0.0     0.0     0.0     0.0   
7235   52218  9.740000e+02   958.0     0.0     0.0     0.0     0.0     0.0   
7236   39558  1.028000e+03   990.0     0.0     0.0     0.0     0.0     0.0   
7237   41298  8.600000e+01    80.0     0.0     0.0     0.0     0.0     0.0   

       ag_003     ag_004  ...    ee_002    ee_003    ee_004     ee_005  \
0         0.0     4136.0  ...   38638.0   20216.0   37878.0    36604.0   
1         0.0     2758.0  ...    2286.0     984.0    3224.0     2524.0   
2         0.0       18.0  ...      30.0      12.0      30.0       26.0   
3         0.0    62040.0  ...  627610.0  376028.0  931828.0  1035236.0   
4         0.0       48.0  ...      74.0       0.0       0.0        0.0   
...       ...        ...  ...       ...       ...       ...        ...   
7233  50354.0  1519364.0  ...  420600.0  189866.0  187228.0    60504.0   
7234      0.0      410.0  ...  437014.0  263728.0  474868.0   342718.0   
7235      0.0    99326.0  ...  492426.0  304914.0  718646.0   503290.0   
7236      0.0      134.0  ...  240834.0  108882.0  226110.0   183064.0   
7237      0.0    87338.0  ...  346606.0  196856.0  530828.0   704182.0   

        ee_006    ee_007    ee_008  ee_009  ef_000  eg_000  
0      86888.0   75222.0   12776.0    44.0     NaN     NaN  
1       3042.0   18908.0     110.0     0.0     0.0     0.0  
2         38.0      54.0       0.0     0.0     0.0     0.0  
3     674626.0  161266.0    3284.0     0.0     0.0     0.0  
4          0.0       0.0       0.0     0.0     0.0     0.0  
...        ...       ...       ...     ...     ...     ...  
7233   54590.0   33294.0    1066.0     0.0     0.0     0.0  
7234  229780.0  107064.0   45860.0     0.0     0.0     0.0  
7235  266236.0  101550.0   68808.0   122.0     0.0     0.0  
7236  189362.0  180186.0  370060.0  1920.0     0.0     0.0  
7237  165946.0    1594.0    1678.0    28.0     0.0     0.0  

[7238 rows x 162 columns]

In [2]:
import numpy as np
a = np.array([[1, 2, 3,],
              [11,22,33]]
            )
b = np.array([[4, 5, 6],
              [44,55,66]]
            )

In [7]:
print(np.r_[b,a])

[[ 4  5  6]
 [44 55 66]
 [ 1  2  3]
 [11 22 33]]


In [6]:
import pandas as pd

(np.c_[a,b])

array([[ 1,  2,  3,  4,  5,  6],
       [11, 22, 33, 44, 55, 66]])