In [4]:
import os

mongo_db_url = os.environ.get('MONGO_DB_URL')

if mongo_db_url:
    print(f'MongoDB URL: {mongo_db_url}')
else:
    print('MONGO_DB_URL environment variable is not set.')

MONGO_DB_URL environment variable is not set.


In [5]:
import os
os.chdir("../")

In [6]:
%pwd

'f:\\End_To_End_project\\Sensor-Fault-Detection'

In [7]:
from Sensor_Fault_Detection.utils.util import read_yaml_file

path = r"F:\End_To_End_project\Sensor-Fault-Detection\configs\schema.yaml"

schema_config = read_yaml_file(path)

In [8]:
schema_config

{'columns': [{'class': 'category'},
  {'aa_000': 'int'},
  {'ac_000': 'int'},
  {'ad_000': 'int'},
  {'ae_000': 'int'},
  {'af_000': 'int'},
  {'ag_000': 'int'},
  {'ag_001': 'int'},
  {'ag_002': 'int'},
  {'ag_003': 'int'},
  {'ag_004': 'int'},
  {'ag_005': 'int'},
  {'ag_006': 'int'},
  {'ag_007': 'int'},
  {'ag_008': 'int'},
  {'ag_009': 'int'},
  {'ah_000': 'int'},
  {'ai_000': 'int'},
  {'aj_000': 'int'},
  {'ak_000': 'int'},
  {'al_000': 'int'},
  {'am_0': 'int'},
  {'an_000': 'int'},
  {'ao_000': 'int'},
  {'ap_000': 'int'},
  {'aq_000': 'int'},
  {'ar_000': 'int'},
  {'as_000': 'int'},
  {'at_000': 'int'},
  {'au_000': 'int'},
  {'av_000': 'int'},
  {'ax_000': 'int'},
  {'ay_000': 'int'},
  {'ay_001': 'int'},
  {'ay_002': 'int'},
  {'ay_003': 'int'},
  {'ay_004': 'int'},
  {'ay_005': 'int'},
  {'ay_006': 'int'},
  {'ay_007': 'int'},
  {'ay_008': 'int'},
  {'ay_009': 'int'},
  {'az_000': 'int'},
  {'az_001': 'int'},
  {'az_002': 'int'},
  {'az_003': 'int'},
  {'az_004': 'int'},


In [9]:
len(schema_config)

3

In [10]:
schema_config.keys()

dict_keys(['columns', 'numerical_columns', 'drop_columns'])

In [1]:
len(schema_config['columns'])

NameError: name 'schema_config' is not defined

In [16]:
import pandas as pd
df =  pd.read_csv(r"F:\End_To_End_project\Sensor-Fault-Detection\artifact\10_03_2023_19_22_11\data_ingetion\feature_store\sensor.csv")


In [20]:
len(df.columns)

171

In [21]:
len(schema_config['columns'])

164

In [23]:
len(schema_config['columns'])==len(df)

False

## data drift 

In [25]:
from scipy.stats import ks_2samp
import numpy as np


In [26]:
d1 = np.arange(10)
d2 = np.arange(10)

d1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
d2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
ks_2samp(d1,d2)

KstestResult(statistic=0.0, pvalue=1.0)

In [29]:
d1 = np.arange(100,200)
d2 = np.arange(10)

d1

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
       126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
       139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151,
       152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164,
       165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177,
       178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190,
       191, 192, 193, 194, 195, 196, 197, 198, 199])

In [30]:
d2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
test = ks_2samp(d1,d2)

In [32]:
test.pvalue

4.2646072253826637e-14

In [33]:
round(test.pvalue)

0

In [18]:
import pandas as pd
train = r"F:\End_To_End_project\Sensor-Fault-Detection\artifact\10_05_2023_16_11_50\data_ingetion\ingested\train.csv"
test = r"F:\End_To_End_project\Sensor-Fault-Detection\artifact\10_05_2023_16_11_50\data_ingetion\ingested\test.csv"


In [19]:
train_df = pd.read_csv(train)
test_df = pd.read_csv(test)

In [39]:
train_df.columns

Index(['class', 'aa_000', 'ab_000', 'ac_000', 'ad_000', 'ae_000', 'af_000',
       'ag_000', 'ag_001', 'ag_002',
       ...
       'ee_002', 'ee_003', 'ee_004', 'ee_005', 'ee_006', 'ee_007', 'ee_008',
       'ee_009', 'ef_000', 'eg_000'],
      dtype='object', length=171)

In [42]:
d1 = train_df['ab_000']
d2 = test_df['ab_000']

In [43]:
ks_2samp(d1,d2)

KstestResult(statistic=0.002505434582366156, pvalue=0.9999999999945326)

In [44]:
columns = list(train_df.columns)
columns

['class',
 'aa_000',
 'ab_000',
 'ac_000',
 'ad_000',
 'ae_000',
 'af_000',
 'ag_000',
 'ag_001',
 'ag_002',
 'ag_003',
 'ag_004',
 'ag_005',
 'ag_006',
 'ag_007',
 'ag_008',
 'ag_009',
 'ah_000',
 'ai_000',
 'aj_000',
 'ak_000',
 'al_000',
 'am_0',
 'an_000',
 'ao_000',
 'ap_000',
 'aq_000',
 'ar_000',
 'as_000',
 'at_000',
 'au_000',
 'av_000',
 'ax_000',
 'ay_000',
 'ay_001',
 'ay_002',
 'ay_003',
 'ay_004',
 'ay_005',
 'ay_006',
 'ay_007',
 'ay_008',
 'ay_009',
 'az_000',
 'az_001',
 'az_002',
 'az_003',
 'az_004',
 'az_005',
 'az_006',
 'az_007',
 'az_008',
 'az_009',
 'ba_000',
 'ba_001',
 'ba_002',
 'ba_003',
 'ba_004',
 'ba_005',
 'ba_006',
 'ba_007',
 'ba_008',
 'ba_009',
 'bb_000',
 'bc_000',
 'bd_000',
 'be_000',
 'bf_000',
 'bg_000',
 'bh_000',
 'bi_000',
 'bj_000',
 'bk_000',
 'bl_000',
 'bm_000',
 'bn_000',
 'bo_000',
 'bp_000',
 'bq_000',
 'br_000',
 'bs_000',
 'bt_000',
 'bu_000',
 'bv_000',
 'bx_000',
 'by_000',
 'bz_000',
 'ca_000',
 'cb_000',
 'cc_000',
 'cd_000',
 '

In [45]:
train_df.shape, test_df.shape

((27141, 171), (9047, 171))

In [54]:
report = {}
def get_drift_report(base_df,current_df, threshold=0.5):
    report={}
    for column in train_df.columns:
        d1 = base_df[column]
        d2 = current_df[column]
        is_same_dist = ks_2samp(d1,d2)
        if threshold<=float(is_same_dist.pvalue):
            is_found=False
        
        else:
            is_found = True
        report.update({column:{
            "p_value":float(is_same_dist.pvalue),
            "drift_status":is_found

            }})
    return report

In [55]:
get_drift_report(train_df, test_df)

{'class': {'p_value': 1.0, 'drift_status': False},
 'aa_000': {'p_value': 0.4764883698189838, 'drift_status': True},
 'ab_000': {'p_value': 0.9999999999945326, 'drift_status': False},
 'ac_000': {'p_value': 0.35175067456218, 'drift_status': True},
 'ad_000': {'p_value': 0.4006664190225946, 'drift_status': True},
 'ae_000': {'p_value': 0.9999999694570323, 'drift_status': False},
 'af_000': {'p_value': 0.9999994660558171, 'drift_status': False},
 'ag_000': {'p_value': 1.0, 'drift_status': False},
 'ag_001': {'p_value': 1.0, 'drift_status': False},
 'ag_002': {'p_value': 0.9999999999990032, 'drift_status': False},
 'ag_003': {'p_value': 0.9997717864093709, 'drift_status': False},
 'ag_004': {'p_value': 0.16345943907467153, 'drift_status': True},
 'ag_005': {'p_value': 0.6602188258611852, 'drift_status': False},
 'ag_006': {'p_value': 0.495326730181905, 'drift_status': True},
 'ag_007': {'p_value': 0.7061008254220469, 'drift_status': False},
 'ag_008': {'p_value': 0.3177354234451508, 'drif

## Zero_ std_columns

In [56]:
train_df

class  aa_000  ab_000  ac_000  ad_000  ae_000  af_000  ag_000  ag_001  \
0       neg      12     0.0    12.0    12.0     0.0     0.0     0.0     0.0   
1       neg     726     NaN     0.0     NaN     0.0     0.0     0.0     0.0   
2       neg  242840     NaN     NaN     NaN     NaN     NaN     0.0     0.0   
3       neg   28800     NaN   252.0   244.0     0.0     0.0     0.0     0.0   
4       neg   58330     NaN  1542.0   308.0     0.0     0.0     0.0     0.0   
...     ...     ...     ...     ...     ...     ...     ...     ...     ...   
27136   neg   29618     NaN     0.0     NaN     0.0     0.0     0.0     0.0   
27137   neg      12     NaN    36.0     NaN     0.0     0.0     0.0     0.0   
27138   neg      20     NaN     8.0     4.0     0.0     0.0     0.0     0.0   
27139   neg   59710     NaN   734.0   696.0     0.0     0.0     0.0     0.0   
27140   pos  517566     NaN     NaN     NaN     NaN     NaN     0.0     0.0   

       ag_002  ...      ee_002     ee_003     ee_004     ee_005     ee_006  \
0         0.0  ...       110.0       44.0       76.0       14.0       36.0   
1         0.0  ...      1764.0      582.0     1882.0    28018.0      300.0   
2         0.0  ...   1782830.0  1274074.0  3193436.0  2725894.0  1562590.0   
3         0.0  ...    309968.0   195206.0   402762.0   222626.0    94058.0   
4         0.0  ...    442744.0   192746.0   382524.0   350810.0   349370.0   
...       ...  ...         ...        ...        ...        ...        ...   
27136     0.0  ...    277876.0   151706.0   404764.0   329882.0   170436.0   
27137     0.0  ...       130.0       44.0       42.0       28.0       20.0   
27138     0.0  ...       320.0       26.0       66.0        0.0        0.0   
27139     0.0  ...    742818.0   369516.0   727576.0   546898.0   301438.0   
27140     0.0  ...  10661418.0  3321906.0  3956102.0  1217588.0   515170.0   

         ee_007    ee_008  ee_009  ef_000  eg_000  
0           0.0       0.0     0.0     0.0     0.0  
1           0.0       0.0     0.0     0.0     0.0  
2      519374.0  347922.0  1716.0     NaN     NaN  
3       53634.0   80034.0  1798.0     0.0     0.0  
4      284108.0  481872.0  9922.0     0.0     0.0  
...         ...       ...     ...     ...     ...  
27136   42222.0   16838.0     0.0     0.0     0.0  
27137      32.0       0.0     0.0     0.0     0.0  
27138       0.0       0.0     0.0     0.0     0.0  
27139   91516.0   12398.0  1040.0     0.0     0.0  
27140  199942.0  162696.0   700.0     NaN     NaN  

[27141 rows x 171 columns]

In [62]:
import pandas as pd

def drop_zero_std_columns(dataframe: pd.DataFrame) -> pd.DataFrame:
    try:
        # Filter only numeric columns
        numeric_df = dataframe.select_dtypes(include=[np.number])
        
        std_dev = numeric_df.std()
        non_zero_std_cols = std_dev[std_dev != 0].index.tolist()
        
        return dataframe[non_zero_std_cols]
    except Exception as e:
        raise e
drop_zero_std_columns(dataframe=train_df)

aa_000  ab_000  ac_000  ad_000  ae_000  af_000  ag_000  ag_001  ag_002  \
0          12     0.0    12.0    12.0     0.0     0.0     0.0     0.0     0.0   
1         726     NaN     0.0     NaN     0.0     0.0     0.0     0.0     0.0   
2      242840     NaN     NaN     NaN     NaN     NaN     0.0     0.0     0.0   
3       28800     NaN   252.0   244.0     0.0     0.0     0.0     0.0     0.0   
4       58330     NaN  1542.0   308.0     0.0     0.0     0.0     0.0     0.0   
...       ...     ...     ...     ...     ...     ...     ...     ...     ...   
27136   29618     NaN     0.0     NaN     0.0     0.0     0.0     0.0     0.0   
27137      12     NaN    36.0     NaN     0.0     0.0     0.0     0.0     0.0   
27138      20     NaN     8.0     4.0     0.0     0.0     0.0     0.0     0.0   
27139   59710     NaN   734.0   696.0     0.0     0.0     0.0     0.0     0.0   
27140  517566     NaN     NaN     NaN     NaN     NaN     0.0     0.0     0.0   

       ag_003  ...      ee_002     ee_003     ee_004     ee_005     ee_006  \
0         0.0  ...       110.0       44.0       76.0       14.0       36.0   
1         0.0  ...      1764.0      582.0     1882.0    28018.0      300.0   
2      2376.0  ...   1782830.0  1274074.0  3193436.0  2725894.0  1562590.0   
3         0.0  ...    309968.0   195206.0   402762.0   222626.0    94058.0   
4         0.0  ...    442744.0   192746.0   382524.0   350810.0   349370.0   
...       ...  ...         ...        ...        ...        ...        ...   
27136     0.0  ...    277876.0   151706.0   404764.0   329882.0   170436.0   
27137     0.0  ...       130.0       44.0       42.0       28.0       20.0   
27138   396.0  ...       320.0       26.0       66.0        0.0        0.0   
27139     0.0  ...    742818.0   369516.0   727576.0   546898.0   301438.0   
27140     0.0  ...  10661418.0  3321906.0  3956102.0  1217588.0   515170.0   

         ee_007    ee_008  ee_009  ef_000  eg_000  
0           0.0       0.0     0.0     0.0     0.0  
1           0.0       0.0     0.0     0.0     0.0  
2      519374.0  347922.0  1716.0     NaN     NaN  
3       53634.0   80034.0  1798.0     0.0     0.0  
4      284108.0  481872.0  9922.0     0.0     0.0  
...         ...       ...     ...     ...     ...  
27136   42222.0   16838.0     0.0     0.0     0.0  
27137      32.0       0.0     0.0     0.0     0.0  
27138       0.0       0.0     0.0     0.0     0.0  
27139   91516.0   12398.0  1040.0     0.0     0.0  
27140  199942.0  162696.0   700.0     NaN     NaN  

[27141 rows x 169 columns]

In [63]:

def split_columns_by_std(dataframe: pd.DataFrame) -> (pd.DataFrame, pd.DataFrame):
    try:
        # Filter only numeric columns
        numeric_df = dataframe.select_dtypes(include=[np.number])
        
        std_dev = numeric_df.std()
        non_zero_std_cols = std_dev[std_dev != 0].index.tolist()
        zero_std_cols = std_dev[std_dev == 0].index.tolist()
        
        non_zero_std_df = dataframe[non_zero_std_cols]
        zero_std_df = dataframe[zero_std_cols]
        
        return non_zero_std_df, zero_std_df
    except Exception as e:
        raise e

non_zero_std, zero_std = split_columns_by_std(train_df)

In [65]:
non_zero_std

aa_000  ab_000  ac_000  ad_000  ae_000  af_000  ag_000  ag_001  ag_002  \
0          12     0.0    12.0    12.0     0.0     0.0     0.0     0.0     0.0   
1         726     NaN     0.0     NaN     0.0     0.0     0.0     0.0     0.0   
2      242840     NaN     NaN     NaN     NaN     NaN     0.0     0.0     0.0   
3       28800     NaN   252.0   244.0     0.0     0.0     0.0     0.0     0.0   
4       58330     NaN  1542.0   308.0     0.0     0.0     0.0     0.0     0.0   
...       ...     ...     ...     ...     ...     ...     ...     ...     ...   
27136   29618     NaN     0.0     NaN     0.0     0.0     0.0     0.0     0.0   
27137      12     NaN    36.0     NaN     0.0     0.0     0.0     0.0     0.0   
27138      20     NaN     8.0     4.0     0.0     0.0     0.0     0.0     0.0   
27139   59710     NaN   734.0   696.0     0.0     0.0     0.0     0.0     0.0   
27140  517566     NaN     NaN     NaN     NaN     NaN     0.0     0.0     0.0   

       ag_003  ...      ee_002     ee_003     ee_004     ee_005     ee_006  \
0         0.0  ...       110.0       44.0       76.0       14.0       36.0   
1         0.0  ...      1764.0      582.0     1882.0    28018.0      300.0   
2      2376.0  ...   1782830.0  1274074.0  3193436.0  2725894.0  1562590.0   
3         0.0  ...    309968.0   195206.0   402762.0   222626.0    94058.0   
4         0.0  ...    442744.0   192746.0   382524.0   350810.0   349370.0   
...       ...  ...         ...        ...        ...        ...        ...   
27136     0.0  ...    277876.0   151706.0   404764.0   329882.0   170436.0   
27137     0.0  ...       130.0       44.0       42.0       28.0       20.0   
27138   396.0  ...       320.0       26.0       66.0        0.0        0.0   
27139     0.0  ...    742818.0   369516.0   727576.0   546898.0   301438.0   
27140     0.0  ...  10661418.0  3321906.0  3956102.0  1217588.0   515170.0   

         ee_007    ee_008  ee_009  ef_000  eg_000  
0           0.0       0.0     0.0     0.0     0.0  
1           0.0       0.0     0.0     0.0     0.0  
2      519374.0  347922.0  1716.0     NaN     NaN  
3       53634.0   80034.0  1798.0     0.0     0.0  
4      284108.0  481872.0  9922.0     0.0     0.0  
...         ...       ...     ...     ...     ...  
27136   42222.0   16838.0     0.0     0.0     0.0  
27137      32.0       0.0     0.0     0.0     0.0  
27138       0.0       0.0     0.0     0.0     0.0  
27139   91516.0   12398.0  1040.0     0.0     0.0  
27140  199942.0  162696.0   700.0     NaN     NaN  

[27141 rows x 169 columns]

In [66]:
zero_std

cd_000
0      1209600.0
1      1209600.0
2      1209600.0
3      1209600.0
4      1209600.0
...          ...
27136  1209600.0
27137  1209600.0
27138  1209600.0
27139  1209600.0
27140  1209600.0

[27141 rows x 1 columns]

In [67]:
    
# importing os.path module  
import os.path 
  
# Path 
path = '/home/User/Documents'
  
# Get the directory name   
# from the specified path 
dirname = os.path.dirname(path) 
  
# Print the directory name   
print(dirname) 

/home/User


In [ ]:


def read_yaml_file(file_path: str)->dict:
    try:
        with open(file_path, 'rb') as yaml_file:
            return yaml.safe_load(yaml_file)
    except Exception as e:
        raise SensorException(e, sys)

In [29]:
from Sensor_Fault_Detection.utils.util  import write_yaml_file,read_yaml_file
from Sensor_Fault_Detection.entity.config_entity import DataValidationConfig,TrainingPipelineConfig

def detect_dataset_drift(base_df, current_df, threshold=0.05) ->bool:
    status = True
    drift_report={}
    for column in base_df.columns:
        d1 = base_df[column]
        d2 = current_df[column]
        is_same_dist = ks_2samp(d1,d2)
        if threshold<=float(is_same_dist.pvalue):
            is_found=False
        else:
            is_found = True
            status = False
        drift_report.update({column:{
            "p_value":float(is_same_dist.pvalue),
            "drift_status":is_found
            }})
    return drift_report

In [30]:
from scipy.stats import ks_2samp
import numpy as np

report = detect_dataset_drift(train_df,test_df,)

In [32]:
path = r"F:\End_To_End_project\Sensor-Fault-Detection\s.yaml"
report = detect_dataset_drift(train_df,test_df,)
write_yaml_file(path,report )

SensorException: Error occurred python script name [f:\End_To_End_project\Sensor-Fault-Detection\Sensor_Fault_Detection\utils\util.py] line number [19] error message [[Errno 2] No such file or directory: 'F:\\End_To_End_project\\Sensor-Fault-Detection\\s.yaml']